const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const RULES = `
# notifee (rest-timer alarm) — the trigger notification's foreground service is referenced by
# exact class name from AndroidManifest.xml ("app.notifee.core.ForegroundService"). Release builds
# run R8/minification (debug builds don't), which can strip or rename these classes since nothing
# in the app code references them directly by name — breaking the alarm/vibration silently in
# release-only builds. notifee ships its own consumer proguard rules, but they weren't enough on
# their own here, so keeping the whole package explicitly.
-keep class app.notifee.core.** { *; }
-keep class io.invertase.notifee.** { *; }
`;

/** Durable version of the manual proguard-rules.pro edit — `android/` is regenerated by every
 * `expo prebuild`, so the rules have to be re-appended by a plugin rather than hand-edited once. */
module.exports = function withNotifeeProguardRules(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const file = path.join(config.modRequest.platformProjectRoot, 'app/proguard-rules.pro');
      const current = fs.readFileSync(file, 'utf8');
      if (!current.includes('app.notifee.core.**')) {
        fs.writeFileSync(file, `${current}\n${RULES}`);
      }
      return config;
    },
  ]);
};
